### ISSUE TITLE
Error during reindexing

### ISSUE THREAD

**Issue by lizard983** [dkd/redsun#3]
Hi,

first off all: thanks for this great plugin!

Unfortunately have a problem with reindexing. I start indexing with this command: 

>  sudo bundle exec rake sunspot:solr:reindex RAILS_ENV=production

After 90% of the process I got everytime the following exception:

> [#####################################################################################################          ] [143836/157975] [ 91.05%] [26:51] [02:38] [    89.27/s]rake aborted!
> NameError: uninitialized constant Contact
> /usr/share/redmine/plugins/redmine_redsun/lib/redmine_redsun/attachment_patch.rb:86:in `description_for_search'
> /var/lib/gems/2.3.0/gems/sunspot-2.2.6/lib/sunspot/util.rb:282:in `__proxy_method__'
> /var/lib/gems/2.3.0/gems/sunspot-2.2.6/lib/sunspot/util.rb:277:in `method_missing'
> /usr/share/redmine/plugins/redmine_redsun/lib/redmine_redsun/attachment_patch.rb:43:in `block (3 levels) in included'
> /var/lib/gems/2.3.0/gems/sunspot-2.2.6/lib/sunspot/util.rb:241:in `instance_eval'
> /var/lib/gems/2.3.0/gems/sunspot-2.2.6/lib/sunspot/util.rb:241:in `instance_eval_with_context'
> /var/lib/gems/2.3.0/gems/sunspot-2.2.6/lib/sunspot/util.rb:102:in `instance_eval_or_call'
> /var/lib/gems/2.3.0/gems/sunspot-2.2.6/lib/sunspot/data_extractor.rb:33:in `value_for'
> /var/lib/gems/2.3.0/gems/sunspot-2.2.6/lib/sunspot/field_factory.rb:39:in `extract_value'
> /var/lib/gems/2.3.0/gems/sunspot-2.2.6/lib/sunspot/field_factory.rb:75:in `populate_document'
> /var/lib/gems/2.3.0/gems/sunspot-2.2.6/lib/sunspot/indexer.rb:111:in `block in prepare_full_update'
> /var/lib/gems/2.3.0/gems/sunspot-2.2.6/lib/sunspot/indexer.rb:110:in `each'
> /var/lib/gems/2.3.0/gems/sunspot-2.2.6/lib/sunspot/indexer.rb:110:in `prepare_full_update'
> /var/lib/gems/2.3.0/gems/sunspot-2.2.6/lib/sunspot/indexer.rb:25:in `block in add'
> /var/lib/gems/2.3.0/gems/sunspot-2.2.6/lib/sunspot/indexer.rb:25:in `map'
> /var/lib/gems/2.3.0/gems/sunspot-2.2.6/lib/sunspot/indexer.rb:25:in `add'
> /var/lib/gems/2.3.0/gems/sunspot-2.2.6/lib/sunspot/session.rb:91:in `index'
> /var/lib/gems/2.3.0/gems/sunspot-2.2.6/lib/sunspot/session_proxy/abstract_session_proxy.rb:11:in `index'
> /var/lib/gems/2.3.0/gems/sunspot-2.2.6/lib/sunspot/session_proxy/retry_5xx_session_proxy.rb:17:in `method_missing'
> /var/lib/gems/2.3.0/gems/sunspot-2.2.6/lib/sunspot/session_proxy/abstract_session_proxy.rb:11:in `index'
> /var/lib/gems/2.3.0/gems/sunspot-2.2.6/lib/sunspot.rb:184:in `index'
> /var/lib/gems/2.3.0/gems/sunspot_rails-2.2.6/lib/sunspot/rails/searchable.rb:264:in `block (2 levels) in solr_index'
> /var/lib/gems/2.3.0/gems/sunspot_rails-2.2.6/lib/sunspot/rails/searchable.rb:405:in `solr_benchmark'
> /var/lib/gems/2.3.0/gems/sunspot_rails-2.2.6/lib/sunspot/rails/searchable.rb:263:in `block in solr_index'
> /var/lib/gems/2.3.0/gems/sunspot_rails-2.2.6/lib/sunspot/rails/searchable.rb:261:in `solr_index'
> /var/lib/gems/2.3.0/gems/sunspot_rails-2.2.6/lib/sunspot/rails/searchable.rb:210:in `solr_reindex'
> /var/lib/gems/2.3.0/gems/sunspot_rails-2.2.6/lib/sunspot/rails/tasks.rb:60:in `block (4 levels) in <top (required)>'
> /var/lib/gems/2.3.0/gems/sunspot-2.2.6/lib/sunspot/class_set.rb:16:in `each'
> /var/lib/gems/2.3.0/gems/sunspot-2.2.6/lib/sunspot/class_set.rb:16:in `each'
> /var/lib/gems/2.3.0/gems/sunspot_rails-2.2.6/lib/sunspot/rails/tasks.rb:59:in `block (3 levels) in <top (required)>'
> /var/lib/gems/2.3.0/gems/sunspot_rails-2.2.6/lib/sunspot/rails/tasks.rb:71:in `with_session'
> /var/lib/gems/2.3.0/gems/sunspot_rails-2.2.6/lib/sunspot/rails/tasks.rb:19:in `block (2 levels) in <top (required)>'
> /var/lib/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
> /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/cli/exec.rb:74:in `load'
> /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
> /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/cli/exec.rb:27:in `run'
> /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/cli.rb:335:in `exec'
> /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
> /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
> /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
> /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/cli.rb:20:in `dispatch'
> /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
> /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/cli.rb:11:in `start'
> /var/lib/gems/2.3.0/gems/bundler-1.14.3/exe/bundle:32:in `block in <top (required)>'
> /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
> /var/lib/gems/2.3.0/gems/bundler-1.14.3/exe/bundle:24:in `<top (required)>'
> /usr/local/bin/bundle:23:in `load'
> /usr/local/bin/bundle:23:in `<main>'
> Tasks: TOP => sunspot:solr:reindex => sunspot:reindex
> (See full trace by running task with --trace)
> 

I use the following environment:

> Environment:
>   Redmine version                3.3.2.stable.16333
>   Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
>   Rails version                  4.2.7.1
>   Environment                    production
>   Database adapter               Mysql2
> SCM:
>   Subversion                     1.9.4
>   Mercurial                      3.9.1
>   Cvs                            1.12.13
>   Git                            2.9.3
>   Filesystem                     
> Redmine plugins:
>   a_common_libs                  2.2.8
>   clipboard_image_paste          1.10
>   luxury_buttons                 3.8.6
>   redmine_agile                  1.4.2
>   redmine_checklists             3.1.5
>   redmine_custom_workflows       0.1.6
>   redmine_drawio                 0.5.0
>   redmine_issue_templates        0.1.3
>   redmine_issues_tree            0.0.9
>   redmine_jstoolbar_ext          0.2.1
>   redmine_jstoolbar_ext_images   0.3.1
>   redmine_lightbox2              0.3.2
>   redmine_people                 1.2.0
>   redmine_redsun                 2.1.0
>   redmine_tags                   3.1.1
>   redmine_thumbnails             0.1.0
>   rm_user_mentions               1.0.0
>   usability                      2.1.8

And solr 4.2.0.2013.03.06.22.32.13.

**Comment by KieranHayes** [comment]
Hi @lizard983,

are you using any other plugins that extend the attachment model?

I think clipboard_image_paste and redmine_people could be responsible for the error message. 

A quick fix would be to disable the Indexing of Attachments by disabling 

this line in the redsun init.rb:

`  # Attachment.send(:include, RedmineRedsun::AttachmentPatch) unless Attachment.included_modules.include? RedmineRedsun::AttachmentPatch
`

**Comment by lizard983** [comment]
Hi @KieranHayes,

thanks so much for your quick answer, you helped me a lot! Years ago I had installed the contacts plugin and in the attachement table in the db were still some attachments of the type contact. They causes the problem. After deleting them the indexing works fine.

Thanks!
